feat: support system property alibabacloud.sessionToken
aliyun/credentials-java pull request #84
Opened 2024-08-16 10:24 UTC by yndu13

##### You need to complete

- [ ] unit tests and/or feature tests
- [ ] documentation is changed or added

2024-08-16 14:48 UTC, JacksonTian commented on src/main/java/com/aliyun/credentials/provider/EnvironmentVariableCredentialsProvider.java
> -        if (accessKeyId.length() == 0) {
这两个地方可能存在为 null。应该 用 StringUtils.isEmpty() 判断

2024-08-16 14:48 UTC, JacksonTian commented on src/main/java/com/aliyun/credentials/provider/EnvironmentVariableCredentialsProvider.java
> -        if (accessKeySecret.length() == 0) {
同上。

2024-08-16 14:49 UTC, JacksonTian commented on src/test/java/com/aliyun/credentials/http/TrueHostnameVerifierTest.java
>          Assert.assertTrue(trueHostnameVerifier.verify(null,null));
这里补一个 断言，传 false，verify 的结果断言为 false

2024-08-16 14:51 UTC, JacksonTian requested changes
有两个问题

2024-08-18 02:36 UTC, yndu13 commented on src/test/java/com/aliyun/credentials/http/TrueHostnameVerifierTest.java
>          Assert.assertTrue(trueHostnameVerifier.verify(null,null));
好的，已处理

2024-08-18 02:38 UTC, yndu13 commented on src/main/java/com/aliyun/credentials/provider/EnvironmentVariableCredentialsProvider.java
> -        if (accessKeyId.length() == 0) {
已处理

2024-08-19 01:41 UTC, JacksonTian approved these changes

2024-08-19 01:42 UTC, merged